### ISSUE TITLE
Off Hand Combat Incompatibility

### ISSUE THREAD

**Issue by Jackiecrazy** [Jackiecrazy/WarDance#15]
BunnyCinnamon/OffHandCombat#5

**Comment by Cixon** [comment]
Is this still going to be added? :O

**Comment by Jackiecrazy** [comment]
I'll have to consider how to best go around it. It could perhaps be added.

**Comment by Cixon** [comment]
could be a optional dependency?

**Comment by Jackiecrazy** [comment]
yes, but it's not possible to make an optional redirect mixin, which is why it's crashing in the first place. Plus, the attack reach and sweep features would have to be handled independently.

**Comment by BunnyCinnamon** [comment]
idk. @Cixon sorry for the ping, I have to ask, is off hand combat _required_? if not then you guys can just take whatever code/feature you need from it so it works similarly, I really don't mind.

**Comment by Cixon** [comment]
> idk. @Cixon sorry for the ping, I have to ask, is off hand combat _required_? if not then you guys can just take whatever code/feature you need from it so it works similarly, I really don't mind.

Not sure what Jackie's opinion is on it since Project:Wardance is his mod entirely, I'm more or less a fan of his work though, Wardance does feature some OffHand functionality, but the mod itself focuses mainly on recreating PvE and PvP.

It plays like a turn-base JRPG, which I enjoy.

However, it's not necessarily a requirement for me in my mod-pack but is highly demanded from my server users.

I personally prefer to use your mod's OffHandCombat functionality in favor of Wardance's just because your mod is regonize by most mod creators thus the chances of cross mod incompatibility is slim to none and your OffHandCombat mod seems to have everything finished.

**Comment by Jackiecrazy** [comment]
code-wise we pretty much do the same thing, so inter-mod compat isn't a big issue. If they work with off hand combat, chances are they'll work with pwd. If not, yell in my general direction.

**Comment by Jackiecrazy** [comment]
this *might* have been fixed in the latest version.
