### ISSUE TITLE
Stagger-locked: posture balancing around high-tier armor [i.e. netherite]

### ISSUE THREAD

**Issue by MrNovado** [Jackiecrazy/WarDance#6]
> Posture regenerates during stagger, so the entity doesn’t get stun-locked.

First of all, very interesting mod, ty for your work!

There's definitely some balancing issue w/ stagger/posture-mechanics tho. For example, if you have netherite armor, husks will pretty much one-hit stagger you. 

I do have `Elenai Dodge 2` & `Epic Fight` installed, and I do not believe either of them changes armor values, but if not for those mods getting away from 3 or more husk-zombies is pretty much impossible.

I don't entirely understand why do you punish players for having high-tier armor in such a way, but it's a little brutish right now in my opinion. As it is now, it completely disincentivizes having netherite armor, which is somewhat weird given vanilla-minecraft' progression. 

> The max time and max number of strikes when staggered are configurable.

Hm, I only see the UI-related options in the config tho? Anyway, the quick and dirty solution for preventing stagger-locking is to add a time-window-immunity for posture upon recovery. Just 1 or 2 seconds should be good enough.

Sort-of like hard armor but for posture only. This way you'd be able to at least try to get away if you are in trouble.

I'm not sure if this should apply to enemies tho, since keeping them staggered is kinda fun.

**Comment by Jackiecrazy** [comment]
The config is per-world because it's server side, look for it in your world save. For the record, I am implementing dodges next version that give i-frames to escape mass beatdowns. The armor bit was an attempt at a meaningful sacrifice between regen speed and defense/fatigue resistance, like in Elenai Dodge. I also absolutely loathe stat-based linear progression, as evidenced by my other mod's attempt to make non-diamond a bit more palatable. In Roman gladiator fights there are indeed heavily armored _secutor_ who strive to beat their lightly armored opponent _retiarius_ before their stamina is exhausted and they get stabbed... anyway, the husk staggering is a dumb oversight on my part that massively increased unarmed melee damage, coupled with the configurable mob buff (default double), which leads to husks hitting 14 posture on hard while a player only has 10 before armor buffs. This one can be configged away for now, I'll be pushing out the update once I finish the rolling mechanic. The posture recharging bit is certainly quite outdated: early on, the posture bar filled and emptied about four times slower, acting more like a stamina bar. Now that it's a fast-gain, fast-loss resource, I ought to make ending stagger just restore posture to its max value.

**Comment by Jackiecrazy** [comment]
Feel free to reopen the issue if you still think it's broken. The mod still requires a lot of playtesting.
